### ISSUE TITLE
SteamUser segfaults when running get_steam_id()

### ISSUE THREAD

**Issue by ShyPixie** [ShyPixie/stlib#1]
steam_user.h on line 26 ( SteamUser()->GetSteamID() )

```
(gdb) run test_get_steam_id.py
Starting program: C:\msys64\mingw64\bin\python3.exe test_get_steam_id.py
[New Thread 5472.0xc5c]
[New Thread 5472.0x2c5c]
[New Thread 5472.0xe60]
[New Thread 5472.0x4b8]
[New Thread 5472.0x5e8]
Setting breakpad minidump AppID = 480
Steam_SetMinidumpSteamID:  Caching Steam ID:  ************************ [API loaded no]

Thread 1 "MainThrd" received signal SIGSEGV, Segmentation fault.
0x0000000054789db4 in steamclient64!hid_write_output_report () from C:\Program Files (x86)\Steam\steamclient64.dll
(gdb)

(gdb) bt
#0  0x0000000054789db4 in steamclient64!hid_write_output_report () from C:\Program Files (x86)\Steam\steamclient64.dll
#1  0x00000000546aeb93 in steamclient64!Steam_TerminateGameConnection () from C:\Program Files (x86)\Steam\steamclient64.dll
#2  0x0000000064d4152b in ?? () from C:\msys64\mingw64\lib\python3.6\site-packages\stlib-0.3.1.dev1-py3.6-mingw.egg\stlib\steam_api-cpython-36m.dll
#3  0x0000000069c10946 in libpython3.6m!_PyCFunction_FastCallDict () from C:\msys64\mingw64\bin\libpython3.6m.dll
#4  0x0000000069c8138c in libpython3.6m!PyEval_EvalFrame () from C:\msys64\mingw64\bin\libpython3.6m.dll
#5  0x0000000069c86200 in libpython3.6m!_PyEval_EvalFrameDefault () from C:\msys64\mingw64\bin\libpython3.6m.dll
#6  0x0000000069c80f0f in libpython3.6m!PyEval_EvalFrame () from C:\msys64\mingw64\bin\libpython3.6m.dll
#7  0x0000000069c81451 in libpython3.6m!PyEval_EvalCode () from C:\msys64\mingw64\bin\libpython3.6m.dll
#8  0x0000000069ca86fd in libpython3.6m!PyGILState_Release () from C:\msys64\mingw64\bin\libpython3.6m.dll
#9  0x0000000069caa94f in libpython3.6m!PyRun_FileExFlags () from C:\msys64\mingw64\bin\libpython3.6m.dll
#10 0x0000000069caaaaf in libpython3.6m!PyRun_SimpleFileExFlags () from C:\msys64\mingw64\bin\libpython3.6m.dll
#11 0x0000000069cbfdce in libpython3.6m!Py_Main () from C:\msys64\mingw64\bin\libpython3.6m.dll
---Type <return> to continue, or q <return> to quit---

#12 0x0000000000407bc3 in ?? ()
#13 0x00000000004013c7 in ?? ()
#14 0x00000000004014fb in ?? ()
#15 0x00007ffbb9663034 in KERNEL32!BaseThreadInitThunk () from C:\WINDOWS\System32\kernel32.dll
#16 0x00007ffbbadd1431 in ntdll!RtlUserThreadStart () from C:\WINDOWS\SYSTEM32\ntdll.dll
#17 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

```

**Comment by ShyPixie** [comment]
@Acidhub

**Comment by ShyPixie** [comment]
It's propably fixed
